version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: camaras_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: camaras_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - camaras_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: camaras_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - camaras_network

volumes:
  postgres_data:

networks:
  camaras_network:
    driver: bridge 